### PR TITLE
Updated awersome to awesome

### PR DESCRIPTION
**Pull request by vaibhavvashishtha**
Corrected the spelling for "awesome" in the README.md file

### CODE REVIEW

**Comment by vaibhavvashishtha** [comment]
Even after approval the code does not seemt o get updated in the readme file

**Comment by vaibhavvashishtha** [comment]
Please do approve the PR, it helps the new users

**Comment by personalcomputer** [comment]
@vaibhavvashishtha The PR needs to be merged for it to be applied to the repo. For that to happen we need help from @bramp. I am just another user for js-sequence-diagrams. :-)

**Comment by vaibhavvashishtha** [comment]
@bramp please help

**Comment by bramp** [comment]
Sorry for the delay! Thanks for this fix! Hopefully next time I'll be faster.

**Pull request merged**
